### PR TITLE
Fixes #246 when no reminder table is registered.

### LINKED ISSUE #246: Unable to resolve service for type 'Orleans.IReminderTable' while attempting to activate 'OrleansDashboard.DashboardRemindersGrain'
Looks like Dashboard needs to use `IReminderTableGrain` in Orleans 2.4.0+ now? [Here](https://github.com/dotnet/orleans/pull/5714)'s the PR that changed it AFAICS.
```
Orleans.Runtime.Dispatcher: Error: Error creating activation for OrleansDashboard.DashboardRemindersGrain. Message NewPlacement Request S127.0.0.1:11111:303392341*cli/514411b1@61a3b394->S127.0.0.1:11111:303392341*grn/D58C58F1/00000000@a23714bb #2639: 

System.InvalidOperationException: Unable to resolve service for type 'Orleans.IReminderTable' while attempting to activate 'OrleansDashboard.DashboardRemindersGrain'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Orleans.Runtime.DefaultGrainActivator.Create(IGrainActivationContext context)
   at Orleans.Runtime.GrainCreator.CreateGrainInstance(IGrainActivationContext context)
   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments)
   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments)
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
```

### PR DESCRIPTION
**Pull request by SebastianStehle**

### CODE REVIEW

File: OrleansDashboard/Metrics/Grains/DashboardRemindersGrain.cs [hunk 1]
```diff
@@ -9,24 +10,30 @@ namespace OrleansDashboard
...
         {
-            _reminderTable = reminderTable;
+            _reminderTable = serviceProvider.GetService(typeof(IReminderTable)) as IReminderTable;
         }
 
         public async Task<Immutable<ReminderResponse>> GetReminders(int pageNumber, int pageSize)
         {
+            if (_reminderTable == null)
+            {
+                return EmptyReminders.AsImmutable();
```
Comment (bddckr) [inline OrleansDashboard/Metrics/Grains/DashboardRemindersGrain.cs]: Just an idea: Instead `EmptyReminders` could be this `Immutable<ReminderResponse>` directly and thus prevent calls to `AsImmutable` when needed. Additionally it would emphasize that `EmptyReminders` itself should stay unchanged throughout the app's lifetime.

Comment (SebastianStehle) [reply OrleansDashboard/Metrics/Grains/DashboardRemindersGrain.cs]: Yeah, I was thinking about it and then realized that immutable is a struct, so there is no allocation. But I will change it.
